### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by quicktrick** [mfechner/nrwl-renovate#62]
Hello Matthias!

I'm so sorry for writing here, I understand this is an absolutely wrong place, but I could not find any other way to connect to you.

I installed Gitlab at FreeBSD using your excellent [guide](https://gitlab.fechner.net/mfechner/Gitlab-docu/blob/master/install/12.7-freebsd.md). I used HTTP configuration.

I use my Gitlab server behind a reverse Nginx proxy working on another host in my local network.  I connect to the proxy via HTTPS and it redirects the traffic to Gitlab HTTP.  Everything works fine except LFS.  I have exactly the same issue as described here: [LFS does not transfer files. file already closed](https://github.com/sameersbn/docker-gitlab/issues/1418) at docker Gitlab thread.  They propose [some solution there](https://github.com/sameersbn/docker-gitlab/issues/1418#issuecomment-491550249), but I don't know their Gitlab configuration to try something similar.

Could you please give me some points on how to solve that?  Do I need to use HTTPS Gitlab configuration from your guide and redirect the traffic from the proxy to https, or maybe there is another way? To be honest, I'm quite a newbie to all that stuff.

My Nginx proxy config is:
```
server {
    listen 443 ssl http2;
    server_name gilab.mydomain.tld;
    server_tokens off;
    root /dev/null;
    charset utf-8;
    client_max_body_size 1024M;

    # SSL settings
    ssl_certificate /etc/letsencrypt/live/gilab.mydomain.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gilab.mydomain.tld/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/gilab.mydomain.tld/chain.pem;

    access_log /var/log/nginx/lab.access.log combined if=$loggable;
    error_log /var/log/nginx/lab.error.log warn;

    location / {
        gzip                    off;
        proxy_read_timeout      300;
        proxy_connect_timeout   300;
        proxy_redirect          off;

        proxy_set_header        Host                $http_host;
        proxy_set_header        X-Real-IP           $remote_addr;
        proxy_set_header        X-Forwarded-Ssl     on;
        proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto   $scheme;

        proxy_pass http://192.168.1.40;
    }
}
```

Thank you very much in advance!

**Comment by quicktrick** [comment]
I coped with that myself. I tried a few variants, but to fix the problem it was enough to do the following:

In `gitlab.yml`:

1. Set the `port` option in section 1 to `443`.
2. Set the `https` option in section 1 to `true`.

(as described in [Using HTTPS](https://gitlab.fechner.net/mfechner/Gitlab-docu/blob/master/install/12.7-freebsd.md#using-https), item 1)

And then `service gitlab restart`

**Comment by mfechner** [comment]
Nice, that you got it working.
